# Generated by Django 5.0.3 on 2024-03-26 08:38

import django.core.validators
import my_music_app.my_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=2, validators=[django.core.validators.MaxLengthValidator(15), my_music_app.my_validators.verify_only_letters_numbers_and_underscore])),
                ('email', models.EmailField(max_length=254)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
