# Generated by Django 5.0.3 on 2024-03-26 14:30

import django.core.validators
import my_music_app.my_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=15, validators=[django.core.validators.MaxLengthValidator(15), my_music_app.my_validators.verify_only_letters_numbers_and_underscore]),
        ),
    ]
