# Generated by Django 5.0.3 on 2024-03-26 13:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=30, unique=True)),
                ('artist_name', models.CharField(max_length=30)),
                ('genre', models.CharField(choices=[('POP', 'Pop Music'), ('JAZZ', 'Jazz Music'), ('R&B', 'R&B Music'), ('ROCK', 'Rock Music'), ('COUNTRY', 'Country Music'), ('DANCE', 'Dance Music'), ('HIPHOP', 'Hip Hop Music'), ('OTHER', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
        ),
    ]
