# Generated by Django 5.0.4 on 2024-04-17 07:26

import exam.my_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20, unique=True, validators=[exam.my_validators.CustomMinLengthValidator(2)])),
                ('first_name', models.CharField(max_length=30, validators=[exam.my_validators.validate_starts_with_letter])),
                ('last_name', models.CharField(max_length=30, validators=[exam.my_validators.validate_starts_with_letter])),
                ('chef', models.BooleanField(default=False)),
                ('bio', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
